spring.application.name=job_portal_backend
spring.datasource.url=jdbc:postgresql://localhost:5432/job_portal_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect