spring.application.name=Learning_demo
management.endpoints.web.exposure.include=*
management.info.env.enabled=true
info.app.name=My simple app
info.app.description=demo app
info.app.version=1.0.0
spring.security.user.name=Harsh
spring.security.user.password=Harsh123

user.name=Gosai
user.role=intern