spring.application.name=Auth_project
spring.datasource.url = jdbc:postgresql://localhost:5432/expence_db
spring.datasource.username = postgres
spring.datasource.password = root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto = update

jwt.security.key=thisisthesecretkeyihaveevercreatedbeforethenightonthebaddoingsomeofthethinkingactivityyoucanneverdothat

server.servlet.context-path=/api/v1.0

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a3d358001@smtp-brevo.com
spring.mail.password=bskPrV3Pai25JLj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=hgosai800@gmail.com

