spring.application.name=spring_mvc_security
spring.security.user.name=harsh
spring.security.user.password=harsh

spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

logging.level.or.springframework.jdbc.core=TRACE