spring.application.name=spring_mvc
country=India, United States, United Kingdom, Canada, Australia, Germany, France, Japan, China, Brazil, South Africa, Italy, Spain, Mexico, Russia
languages=Go, Java, Rust, Python, C++, JavaScript, Rust, TypeScript
currentDevices = Android, IOS, mac, Windows, Ubontu, Rasberrypie, Tablet